FROM nginx:1.9.0
MAINTAINER Ricky Walker "ricky.walker@jediq.com"
#NAME sprint0/nginx

#ENV DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 --dns 127.0.0.1"

RUN apt-get -y update

RUN apt-get -y install puppet
#RUN apt-get -y install librarian-puppet

